name: edunews
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  fonts:
    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/Playfair_Display/PlayfairDisplay-Regular.ttf
          weight: 400
        - asset: assets/fonts/Playfair_Display/PlayfairDisplay-Medium.ttf
          weight: 500        
        - asset: assets/fonts/Playfair_Display/PlayfairDisplay-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Playfair_Display/PlayfairDisplay-Bold.ttf
          weight: 700        
        - asset: assets/fonts/Playfair_Display/PlayfairDisplay-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Playfair_Display/PlayfairDisplay-Black.ttf
          weight: 900
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
